import LegalPageLayout from '@/components/ui/LegalPageLayout';

const sections = [
  { id: 'acceptance', title: 'Acceptance' },
  { id: 'eligibility', title: 'Eligibility' },
  { id: 'account', title: 'Account' },
  { id: 'acceptable-use', title: 'Acceptable Use' },
  { id: 'ip', title: 'Intellectual Property' },
  { id: 'subscriptions', title: 'Subscriptions' },
  { id: 'ai-disclaimer', title: 'AI Disclaimer' },
  { id: 'liability', title: 'Liability' },
  { id: 'warranties', title: 'Warranties' },
  { id: 'termination', title: 'Termination' },
  { id: 'changes', title: 'Changes' },
  { id: 'contact', title: 'Contact Us' },
];

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="March 17, 2026" sections={sections}>
      <section id="acceptance">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By downloading, installing, or using the Maxly mobile application ("App") operated by Adam Solutions ("we," "our," or "us"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.
        </p>
      </section>

      <section id="eligibility">
        <h2>2. Eligibility</h2>
        <p>
          You must be at least 14 years of age to use Maxly. If you are between 14 and 18 years of age, you must have the consent of a parent or legal guardian. By using the App, you represent and warrant that you meet these eligibility requirements.
        </p>
      </section>

      <section id="account">
        <h2>3. Account Registration</h2>
        <p>
          To use certain features, you must create an account. You agree to provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
        </p>
      </section>

      <section id="acceptable-use">
        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the App for any unlawful purpose</li>
          <li>Upload photos of other people without their consent</li>
          <li>Attempt to reverse-engineer, decompile, or disassemble the App</li>
          <li>Interfere with or disrupt the App's functionality or servers</li>
          <li>Use automated systems or bots to access the App</li>
          <li>Share or distribute AI analysis results in a harassing or harmful manner</li>
          <li>Misrepresent your identity or impersonate another person</li>
        </ul>
      </section>

      <section id="ip">
        <h2>5. Intellectual Property</h2>
        <p>
          The App, including all content, features, and functionality, is owned by Adam Solutions and protected by copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, modify, or create derivative works of any part of the App without our prior written consent.
        </p>
      </section>

      <section id="subscriptions">
        <h2>6. Subscriptions & Payments</h2>
        <p>
          Maxly offers premium features through subscription plans. Subscriptions are billed through the Apple App Store or Google Play Store. All payments are processed by the respective platform. You may cancel your subscription at any time through your device's subscription settings.
        </p>
        <p>
          Trial periods, if offered, automatically convert to paid subscriptions unless cancelled before the trial period ends. Refunds are subject to the policies of the Apple App Store or Google Play Store.
        </p>
      </section>

      <section id="ai-disclaimer">
        <h2>7. AI Analysis Disclaimer</h2>
        <p>
          Maxly's facial analysis, scores, and recommendations are generated by AI algorithms and are provided for informational and entertainment purposes only. They do not constitute medical, psychological, or professional advice. Results may vary and should not be used as the sole basis for personal decisions.
        </p>
      </section>

      <section id="liability">
        <h2>8. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, Adam Solutions shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or data, arising out of or in connection with your use of the App.
        </p>
      </section>

      <section id="warranties">
        <h2>9. Disclaimer of Warranties</h2>
        <p>
          The App is provided "as is" and "as available" without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
        </p>
      </section>

      <section id="termination">
        <h2>10. Termination</h2>
        <p>
          We may terminate or suspend your account and access to the App at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties. Upon termination, your right to use the App ceases immediately.
        </p>
      </section>

      <section id="changes">
        <h2>11. Changes to These Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will notify you of changes by updating the "Last updated" date. Your continued use of the App after any changes constitutes acceptance of the new Terms.
        </p>
      </section>

      <section id="contact">
        <h2>12. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us:</p>
        <ul>
          <li>Email: <a href="mailto:support@maxlyapp.com">support@maxlyapp.com</a></li>
        </ul>
      </section>
    </LegalPageLayout>
  );
}
